#!/usr/bin/env bash
# Parallel dispatch configuration.
# Override any value via environment variable.

# --- Consume-test parallelism ---
GREENAPPLE_MAX_PARALLEL_BATCHES="${GREENAPPLE_MAX_PARALLEL_BATCHES:-3}"
GREENAPPLE_MAX_SAME_AGENT="${GREENAPPLE_MAX_SAME_AGENT:-2}"
GREENAPPLE_BATCH_SIZE="${GREENAPPLE_BATCH_SIZE:-5}"

# --- Phase-level parallelism ---
GREENAPPLE_RECON_PARALLEL="${GREENAPPLE_RECON_PARALLEL:-2}"
GREENAPPLE_EXPLOIT_PARALLEL="${GREENAPPLE_EXPLOIT_PARALLEL:-2}"

# --- Timeouts ---
GREENAPPLE_SUBAGENT_TIMEOUT="${GREENAPPLE_SUBAGENT_TIMEOUT:-300}"
